name: AntiCheat
version: 0.0.1
api: 5.0.0
main: Lee1387\AntiCheat
author: Lee1387

commands:
  anticheat:
    description: AntiCheat Commands
    permission: anticheat.perms
    usage: /anticheat help

permissions:
  anticheat.perms:
    description: OP Perms for AntiCheat
    default: op
